### GENERAL SETTINGS ###
gems:
  - jekyll-sitemap

# Site settings
title: Slate Horse
description: "A software development consultancy. Actually, scratch that, we help good people build great software to solve interesting problems."
analytics: UA-73637610-1
baseurl: "" #important: start with /
url: "https://slatehorse.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#009DFF" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: https://twitter.com/slatehorse
  - title: github
    url: https://github.com/slatehorse

company_name: Slate Horse Limited
company_number: 9832352
vat_number: 224636025   

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Cobweb Buildings,
    - The Lane,
    - Lyford, 
    - OX12 0EE,
    - United Kingdom.
email: hello@slatehorse.com
tel: +44 (0)7841 757984


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Mark Webber
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: https://twitter.com/handle
  - name: Paul Jameson
    position: Lead Designer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: https://twitter.com/handle
  - name: Laura Sommers
    position: Lead Developer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Martin Blunt
    position: Marketing
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: https://twitter.com/handle
    
# Clients information. Shown on Home and About pages.
clients:
  - name: Kudos Innovations Ltd.
    img: logo-kudos.png
    url: https://growkudos.com
  - name: Oxford University Hospitals NHS Trust
    img: logo-ouh.png
    url: http://oxfordbrc.nihr.ac.uk
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Slate Horse is a consultancy based in Oxfordshire. We help companies build amazing development teams and create effective technical strategies. We also love making things."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO
